# Generated by Django 4.2 on 2026-09-12 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='foto',
            old_name='Album',
            new_name='album',
        ),
    ]
